services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bookdb'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
