spring:
  application:
    name: book-management
  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true
  
  # データベース接続設定
  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # Flyway設定
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  # JOOQ設定
  jooq:
    sql-dialect: POSTGRES
